# Generated by Django 2.2 on 2019-08-21 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190821_1404'),
    ]

    operations = [
        migrations.CreateModel(
            name='dj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('job', models.CharField(max_length=20)),
                ('sal', models.FloatField()),
            ],
            options={
                'db_table': 'dj1',
                'managed': False,
            },
        ),
    ]
