# Generated by Django 2.2 on 2019-08-21 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_dj'),
    ]

    operations = [
        migrations.DeleteModel(
            name='dj',
        ),
    ]
