# Generated by Django 2.2 on 2019-08-24 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='val',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v1', models.IntegerField()),
                ('v2', models.IntegerField()),
                ('v3', models.CharField(default=0, max_length=10)),
            ],
        ),
    ]
