# Generated by Django 2.2 on 2019-08-20 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='helth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heartbeat', models.IntegerField()),
                ('himoglobin', models.IntegerField()),
                ('breathingrate', models.IntegerField()),
            ],
        ),
    ]
